first commit
techmanti/wordpress pull request #5
Opened 2022-11-23 18:54 UTC by rogermov

agora foi

2022-11-24 00:02 UTC, francardoso93 commented
`terraform fmt --recursive` para formatar certinho os espaços (pra deixar no padrão)

2022-11-24 00:10 UTC, francardoso93 commented
A divisão de pastas em relação a separar os live modules dos shared modules está correta! 
Fiquei com dúvidas sobre os nomes escolhidos (Nomear coisas é sempre difiícil):
- Por que a pasta do live module chama global?
- Por que a pasta do shared module chama latest?
- Por que o `main` no shared module se chama `main_script`?

2022-11-24 00:21 UTC, francardoso93 requested changes

2022-11-24 00:21 UTC, francardoso93 commented on global/main.tf
> +  database_password       = "wPT3chM4n!Db"        //password for user database
Publicar senhas no GitHub é uma falha de segurança.

2022-11-24 00:21 UTC, francardoso93 commented on global/main.tf
> +  database_password       = "wPT3chM4n!Db"        //password for user database
Pra fazer da forma correta, o correto é que esse valor venha como um input do sistema. 
Exemplo:
terraform apply -var="database_password=$DATABASE_PASSWORD"

Esse valor do input fica protegido como uma variável de ambiente, ou ainda melhor, como um SEGREDO (ex: GitHub secrets)

2022-11-24 00:21 UTC, francardoso93 commented on modules/latest/main_script.tf
> +
Deixa só uma linha em branco no final

2022-11-24 00:21 UTC, francardoso93 commented on global/s3/terraform.tfstate.backup
> +{
Arquivo de state tem diversas informações confidenciais, como senhas, ids e etc que podem ser exploradas por um hacker. Portanto, publicá-lo no GitHub é uma falha de segurança.

2022-11-24 00:21 UTC, francardoso93 commented on modules/latest/main_script.tf
> +  ami                    = var.IsUbuntu ? data.aws_ami.ubuntu.id : data.aws_ami.linux2.id
Top! O restante da instalação do wordpress vai funcionar igual em qualquer uma dessas imagens?

2022-11-24 00:21 UTC, francardoso93 commented on .gitignore
> +wordpress_tf.sh
Esses arquivos parecem importantes, e deveriam ser commitados.
Se não, eu não consigo rodar isso (Nem você no futuro depois de apagar esses da sua máquina local, ou se fosse trabalhar em outro PC)

2022-11-24 00:21 UTC, francardoso93 commented on modules/latest/main_script.tf
> +}
Precisa? A quantidade de IPs fixos é limitada, e geralmente não precisa. Não dá pra pegar o IP dinâmico da EC2 e depois usar para fazer a `connection`? (linha 224)

2022-11-25 11:19 UTC, rogermov commented on modules/latest/main_script.tf
> +
Tranquilo! A prática é sempre deixar só uma linha no final?

2022-11-25 11:20 UTC, rogermov commented on global/s3/terraform.tfstate.backup
> +{
Coloquei no .gitignore!

2022-11-25 11:21 UTC, rogermov commented on modules/latest/main_script.tf
> +  ami                    = var.IsUbuntu ? data.aws_ami.ubuntu.id : data.aws_ami.linux2.id
Sim! Tanto para ubuntu quanto para linux!

2022-11-25 11:23 UTC, rogermov commented on .gitignore
> +wordpress_tf.sh
Verdade, coloquei para commit

2022-11-25 11:55 UTC, rogermov commented on modules/latest/main_script.tf
> +}
Para ser sincero eu não cheguei a testar, eu criei somente para ter um ip estático para conexão.

2022-11-25 13:24 UTC, rogermov commented on global/main.tf
> +  database_password       = "wPT3chM4n!Db"        //password for user database
Realmente, concordo! fiz por variável e com um input no sistema!

2022-11-25 19:18 UTC, rogermov commented
> A divisão de pastas em relação a separar os live modules dos shared modules está correta! Fiquei com dúvidas sobre os nomes escolhidos (Nomear coisas é sempre difiícil):
> 
> * Por que a pasta do live module chama global?
> * Por que a pasta do shared module chama latest?
> * Por que o `main` no shared module se chama `main_script`?



> A divisão de pastas em relação a separar os live modules dos shared modules está correta! Fiquei com dúvidas sobre os nomes escolhidos (Nomear coisas é sempre difiícil):
> 
> * Por que a pasta do live module chama global?
> * Por que a pasta do shared module chama latest?
> * Por que o `main` no shared module se chama `main_script`?

1- Global para indentificar aonde está os tf principais.
2- Eu tinha feito várias pastas para testar meus codigos e esse era o mais recente.
3- `main_script` para separar dos outros `main` porque antes não estava rodando em pastas

Provavelmente sim, mas tem alguma sugestão que gostaria de dar para as pastas e o pro `main_script`?

2022-11-28 14:25 UTC, francardoso93 commented on global/main.tf
> +  database_password       = "wPT3chM4n!Db"        //password for user database
Boa, agora precisa remover desse arquivo

2022-11-28 14:28 UTC, francardoso93 commented on global/main.tf
> +  database_password       = "wPT3chM4n!Db"        //password for user database
E esse valor explicito da senha pode sumir :)

2022-11-28 14:33 UTC, francardoso93 commented on .gitignore
> +terraform.tfstate.backup
Ignora de qualquer pasta, não apenas da raíz

2022-11-28 14:43 UTC, francardoso93 commented on modules/latest/main_script.tf
> +}
Pode testar, por favor?

2022-11-28 14:45 UTC, francardoso93 commented on .gitignore
> +terraform.tfstate.backup
Depois de atualizar o .gitignore, e antes do git add, executar esse comando:
`it rm -r --cached . `
Motivo: Arquivo de state ainda está subindo aqui

2022-11-28 19:54 UTC, francardoso93 commented on global/s3/terraform.tfstate.backup
> +{
Depois de atualizar o .gitignore, e antes do git add, executar esse comando:
git rm -r --cached .
Motivo: Arquivo de state ainda está subindo aqui

2022-11-28 19:55 UTC, francardoso93 commented on modules/latest/main_script.tf
> +
Isso :)

2022-11-28 20:11 UTC, francardoso93 commented
> 1- Global para indentificar aonde está os tf principais. 2- Eu tinha feito várias pastas para testar meus codigos e esse era o mais recente. 3- `main_script` para separar dos outros `main` porque antes não estava rodando em pastas
> 
> Provavelmente sim, mas tem alguma sugestão que gostaria de dar para as pastas e o pro `main_script`?

Organizar/Nomear coisas não é simples kkkk a dica é também tentar olhar o que as pessoas/comunidade estão organizando código Terraform, pesquisando no GitHub, e vendo o que faz sentido para o nosso cenário 

1 - O nome "global" não diz muito.. Um melhor nome é tentar agrupar o todo, o que é tudo isso junto? É um "Wordpress"? Talvez o nome "wordpress" seja melhor. Ou outro nome que faça sentido como o por que esse código está todo agrupado ali. Outra coisa é que talvez esse "main" global não precisa obrigatoriamente estar dentro de uma pasta. Se nós só formos ter um único live module nesse repo, ele pode estar fora da pasta, direto na raiz. Não é questão de certo ou errado, e mais vantagens e desvantagens.
2 - Blz você colocou a versão do módulo, mas não o nome dele. O ideal é que a pasta tenha o nome do módulo. Pensar: Por que esse código está agrupado junto? É igual terminar de escrever um texto, e ter que dar um título pra ele.
3 - Renomear para "main"

2022-11-29 12:43 UTC, rogermov commented on global/main.tf
> +  database_password       = "wPT3chM4n!Db"        //password for user database
Boa! Fiz e tá tudo ok!

2022-11-29 12:44 UTC, rogermov commented on global/s3/terraform.tfstate.backup
> +{
Não sabia desse comando kkkk bom demais!

2022-11-29 12:44 UTC, rogermov commented on modules/latest/main_script.tf
> +}
Testei e funcionou! Com a IP estático, cria algum tipo de bloqueio?

2022-11-29 19:10 UTC, rogermov commented
> > 1- Global para indentificar aonde está os tf principais. 2- Eu tinha feito várias pastas para testar meus codigos e esse era o mais recente. 3- `main_script` para separar dos outros `main` porque antes não estava rodando em pastas
> > Provavelmente sim, mas tem alguma sugestão que gostaria de dar para as pastas e o pro `main_script`?
> 
> Organizar/Nomear coisas não é simples kkkk a dica é também tentar olhar o que as pessoas/comunidade estão organizando código Terraform, pesquisando no GitHub, e vendo o que faz sentido para o nosso cenário
> 
> 1 - O nome "global" não diz muito.. Um melhor nome é tentar agrupar o todo, o que é tudo isso junto? É um "Wordpress"? Talvez o nome "wordpress" seja melhor. Ou outro nome que faça sentido como o por que esse código está todo agrupado ali. Outra coisa é que talvez esse "main" global não precisa obrigatoriamente estar dentro de uma pasta. Se nós só formos ter um único live module nesse repo, ele pode estar fora da pasta, direto na raiz. Não é questão de certo ou errado, e mais vantagens e desvantagens. 2 - Blz você colocou a versão do módulo, mas não o nome dele. O ideal é que a pasta tenha o nome do módulo. Pensar: Por que esse código está agrupado junto? É igual terminar de escrever um texto, e ter que dar um título pra ele. 3 - Renomear para "main"

Então, minha cabeça vira um trevo sempre que vou renomear algo kkkkkk 
1 - Então, enquanto vou fazendo os objetivos/projetos sempre fico olhando no github alheio para ter uma ideia sempre sobre como renomear/organizar, para ficar mais claro em ambiente de produção, mas ainda assim me confundo bastante. Minha ideia era deixar fora mesmo o "Main" e concordo com oque disse! Eu renomeei e caso preciso de uma nova alteração ou você tenha alguma outra ideia, nós debatemos.

2 - Certo, refiz como orientado!

3- Correção feita!

2022-11-29 21:32 UTC, francardoso93 commented on modules/latest/main_script.tf
> +}
Só não é uma boa prática, a não ser que tenhamos um bom motivo pra isso.
IPs fixos custam $$$
Se ele poder ser dinamico, bora dinamico

2022-11-30 12:07 UTC, rogermov commented on modules/latest/main_script.tf
> +}
Tranquilo, alterado!

2022-11-30 18:09 UTC, francardoso93 approved these changes

2022-12-01 10:53 UTC, merged